### ISSUE TITLE
lots of stuff in obs repo

### ISSUE THREAD

**Issue by a-dekker** [wdehoog/donnie#1]
Hello Willem-Jan,

Recently all kinds of qt5 media and systemd packages where added to your obs repo. A version --dup or zypper up will install these packages if your repo is enabled. And I am not sure in what state they are.

I really like your Donnie app, by far the best UPnP player around for Sailfish. So any plans to move the player and related libraries to openrepos and/or the harbour store?

**Comment by wdehoog** [comment]
Hi,

Sorry for that. I did not think of it. In fact I did not think of anyone using Donnie. I am still working on it since there is so much going wrong.

When I have some more confidence I would like to ask openrepos for admission.

In the mean time can you use something like 'pkcon update donnie' to update only one package?

(The systemd package supresses a message in journal, in qtmultimedia I try to fix buffering issues with qml audio and internet streams and the statefs-providers packages is specially for my phone (bacon).)

**Comment by a-dekker** [comment]
Of course pkcon update donnie works, but as I always upgrade Sailfish by command line, it upgrades everything (unless I disable your repo in advance).
Just upgraded to 2.1.2.3 with your packages installed and all went fine btw.

In my opinion Donnie is in a state for release in openrepos. Had some issues with Bose Soundtouch at a friends house, but at home it works pretty stable. I have seen apps in a far worse state in openrepos, but it is up to you if your are not comfortable with it.

**Comment by wdehoog** [comment]
I have a sh*** wifi at home and having lots of problems handling the (network) errors that occur.

Your opinion made me sent a request to openrepos so we will see how it goes.

Maybe it is not apropriate to ask it here in an issue but may I ask how you use Donnie? What server and what render?

**Comment by a-dekker** [comment]
Anyone can create an account at openrepos (as a developer or regular user), it's that simple.
I do have minidlna on the server side and mostly use upmpdcli/UpMPD (kind of wrapper around mpd) on the client side. And sometimes I use Sailfish as the renderer.

**Comment by wdehoog** [comment]
And on what phone?

I am now creating a subproject on OBS (https://api.merproject.org/project/show/home:wdehoog:donnie) so it's repo will not contain non related stuff. If all works well there will be two versions build of donnie. The latest one and a sort of stable one.

**Comment by a-dekker** [comment]
Jolla 1 atm, but will switch to Xperia X soon.
I'll enable to your new repo and looking forward to the further development of this.
And I'll close the issue :-)

**Comment by wdehoog** [comment]
FYI Donie has just added it on OpenRepos.

**Comment by a-dekker** [comment]
And first 5 star rating given on OpenRepos
