### ISSUE TITLE
Slide down  menu; line too long-wide.

### ISSUE THREAD

**Issue by ghost** [wdehoog/donnie#12]

**Comment by wdehoog** [comment]
You mean one of the pully menu labels is too long? Which one?

**Comment by Caballlero** [comment]
/home/carlos/Descargas/Captura_20171014_001.jpeg

**Comment by wdehoog** [comment]
I have still no idea what you mean. Did got a notification from github but I don't see anything extra appear.
Can you provide some more information?

**Comment by ghost** [comment]
i am  sorry @wdehood i tryed many time to upload 2 picture to 
show  you the issue, but I do not know why github is not accepting me upload the pictures here....

**Comment by ghost** [comment]
**Thx** almost done, still need a little bit more. Wide Line=**100%** but Long Line= **99.98%** need a little bit more until it reaches the ends of the screen at both ends.

**Comment by ghost** [comment]
Fixed, Thank you.
