### ISSUE TITLE
Change "about" to a second option ,then "settings" be the first. Slide down menu.  

### ISSUE THREAD

**Issue by ghost** [wdehoog/donnie#14]
Ajustes      -> Settings
Acerca de -> About

![captura_20171010_001](https://user-images.githubusercontent.com/24536606/31585908-a11a9e1e-b197-11e7-8b7c-0473cbf205c9.png)

**Comment by ghost** [comment]
This it is not a issue , but mostly a sailfish app "About" option always going to the last option on a sliding menu. you have the final word whether to leave it or change it. Just notifying....

**Comment by wdehoog** [comment]
Thanks. You are right. I'll change it.

**Comment by ghost** [comment]
Thx.
