### ISSUE TITLE
Feature Request: Using Sailfish as Server

### ISSUE THREAD

**Issue by ghost** [wdehoog/donnie#20]
Hi. I like your App. Its the only upnp App for SailfishOS to use with my Network Receiver whitch I can seek with.  So could you add the possibility to use the Jolla as a Server that I can play songs stored in my Jolla on my Receiver? I know Jupii can do it. But with this app seeking is not supported.

**Comment by wdehoog** [comment]
Sorry but I am not going to work on that. It will be a major task and I have no personal interest in such a feature. Since Jupii already supports seek I suggest you help on getting that working in your setup.

**Comment by ghost** [comment]
Okay. Thanks. I'm already in contact with the Jupii Dev
