### ISSUE TITLE
Feature request: Download arbitrary files

### ISSUE THREAD

**Issue by zwieberl** [wdehoog/donnie#27]
My usecase: get pictures from my Sony camera onto the phone. 
This app is one of the very few which are actually able to detect and connect to my camera. I can browse there, but can't see or download pictures.
Is it possible to add such a feature? 
I do know C++, so I might also be able to help.

**Comment by wdehoog** [comment]
It probably is possible to add such a feature but I am not going to do that. Busy with other stuff and it would not be a sensible feature for a upnp controller/music player.

If you want to add it yourself you might start in Browse.qml where the items are filtered on "upnp:class" for starting with "object.item.audioItem". Maybe your images start with "object.item.imageItem" (see http://www.upnp.org/specs/av/UPnP-av-ContentDirectory-v1-Service.pdf)

Adjust the "source:" of the Image in the "delegate: ListItem {" to use the url of your image so you can view them in the browse list.

And also add a new MenuItem to the ContextMenu (still Browse.qml) where you can use some javascript to download the image.

success.
