### ISSUE TITLE
aarch64 install?

### ISSUE THREAD

**Issue by poetaster** [wdehoog/donnie#30]
Any chance of building this so newer versions (>4) of SFOS can run it?

**Comment by poetaster** [comment]
I'm not sure if it's just a matter of bumping the meta in obs? You've set it to arm7 latest, maybe it's just an additional repository stanza and you're done?

Thanks in any case!

**Comment by wdehoog** [comment]
I have added a aarch64 repo and it seems to have built it. Is that what you want? As for the SFOS version I don't think one can select that. I looks like OBS just builds for the target one that the admins have configured.

**Comment by poetaster** [comment]
Thank you! I'll try the builds and let you know if they work.

**Comment by poetaster** [comment]
Great! Did:

```
ssu ar donnie https://repo.sailfishos.org/obs/home:/wdehoog:/donnie/sailfish_latest_aarch64
pkcon refresh
zypper install libupnp6
zypper install libupnpp
zypper install donnie

```
Works exactly as you'd expect. I'll pass on the news for others on the forum. When I find some time I'll see if I can add / assist with tickets.

Thanks!

**Comment by poetaster** [comment]
And closing.

**Comment by poetaster** [comment]
Just a note. I've built your 0.9 tag on chum:testing at obs with slightly updated libs. They install fine and donnie works fine. The libraries also don't conflict with other versions floating around. So donnie will be available on chum. At the moment I'm maintainer of the package but you could always step in if you wish. Thanks for donnie!
