### ISSUE TITLE
Cover artist build-in into files not work

### ISSUE THREAD

**Issue by ghost** [wdehoog/donnie#9]
- mp3 cover artist built-in look like no work, 
Could be nice this features in donnie

**Comment by wdehoog** [comment]
The idea is that the media server provides the url for the album art (property 'upnp:albumArtURI'). Donnie only looks for this property (in the meta data) and uses it when available.

The media server should have support for it. I am using minimserver which does that. See http://minimserver.com/ug-library.html#Artwork. Maybe minidlna does it as well. What are you using?

How would you add the ability to extract and use the embedded cover image? The mp3 is not even 'seen' by donnie so it would have to download it by itself as well. 

It is a pity the built in Qt Audio player does not implement this feature then it would be easy to implement.

**Comment by ghost** [comment]
i use **Rygel**:https://wiki.gnome.org/action/show/Projects/Rygel?action=show&redirect=Rygel

**Comment by wdehoog** [comment]
The media export plugin seems to support extracting meta data so it should work. Does donnie show no image whatsoever for any mp3? 

Maybe you can uncomment line 40 of Browse.qml (//console.log(contentsJson) to see what rygel sends. Then check if there is an album art uri and if this uri actually works.

**Comment by ghost** [comment]
nop donnie not show any image. Note that I only use built-in cover art into the file like mostly .flac I have a few files .mp3 with built-in cover art. so I only tested donnie  with .mp3 files . I will do a  heavy test tomorrow. 
Ok i will do some test about your suggestions.
Thanks ...

**Comment by wdehoog** [comment]
Which rygel plugin do you use for the server? Tracker or Media Export?

**Comment by wdehoog** [comment]
Just verified rygel with the media-export plugin does extract album art from mp3 and flac files. The covers were shown.

**Comment by ghost** [comment]
carlos@debian-sony:~$ rygel
Rygel-Message: rygel-acl.vala:143: No se ha encontrado ninguna política de ACL alternativa. Usando «allow»
Rygel-Message: Iniciando Rygel v0.32.1…
Rygel-Tracker-Message: rygel-tracker-item-factory.vala:68: Using /home/carlos/Música as upload directory for object.item.audioItem.musicTrack
Rygel-Tracker-Message: rygel-tracker-item-factory.vala:68: Using /home/carlos/Vídeos as upload directory for object.item.videoItem
Rygel-Tracker-Message: rygel-tracker-item-factory.vala:68: Using /home/carlos/Imágenes as upload directory for object.item.imageItem.photo
RygelCore-Message: Existe un nuevo complemento «Tracker» disponible
RygelCore-Message: Existe un nuevo complemento «Playbin» disponible
RygelCore-Message: Existe un nuevo complemento «MediaExport» disponible
MediaExport-Message: «file:///home/carlos/V%C3%ADdeos» recolectado
MediaExport-Message: rygel-media-export-harvesting-task.vala:300: Harvesting of file:///home/carlos/V%C3%ADdeos done in 0.019104
MediaExport-Message: «file:///home/carlos/M%C3%BAsica» recolectado
MediaExport-Message: rygel-media-export-harvesting-task.vala:300: Harvesting of file:///home/carlos/M%C3%BAsica done in 0.025028
MediaExport-Message: «file:///home/carlos/Im%C3%A1genes» recolectado
MediaExport-Message: rygel-media-export-extract.vala:163: Started with descriptors 3 (in) 4 (out)
MediaExport-Message: rygel-media-export-extract.vala:163: Started with descriptors 3 (in) 4 (out)
MediaExport-Message: rygel-media-export-extract.vala:163: Started with descriptors 3 (in) 4 (out)
MediaExport-Message: rygel-media-export-harvesting-task.vala:300: Harvesting of file:///home/carlos/Im%C3%A1genes done in 0.033376

**Comment by ghost** [comment]
Look like use MediaExport plugin.
What version of Rygel you tested? I will update Rygel to the last version to see what happen.

**Comment by wdehoog** [comment]
Rygel 0.28.3 on xubuntu (in a virtual box).

/etc/rygel.conf
[Tracker]
enabled=false

[MediaExport]
enabled=true
title=@REALNAME@'s media on @PRETTY_HOSTNAME@
uris=@MUSIC@;@VIDEOS@;@PICTURES@;/media/sf_temp/media/Music/Psychedelic
extract-metadata=true
monitor-changes=true
monitor-grace-timeout=5
virtual-folders=true

**Comment by ghost** [comment]
...after a heavy test Donnie-cover-art **work**. But only work with cover.* art included into the folder of track. but not into of track. so   there are 2 ways to display a cover art on a track. Usually I insert the cover.* inside the track, not on the side  of the tracks.

**Comment by wdehoog** [comment]
Weird. I tested with a directory containing three mp3s and one flac, no images, only embedded album covers. Rygel handled them just fine.

**Comment by ghost** [comment]
it's fine. Just out of curiosity you can tell me how many pixels is the image of the album encrusted inside in your test  track?

**Comment by wdehoog** [comment]
323x321 and 500x500

**Comment by ghost** [comment]
yes me too. 500x500p  is the standard.

**Comment by ghost** [comment]
I still need do some  on my side before to close this PR
Thx.

**Comment by ghost** [comment]
After  a deep test I found a issue ( files I tests light corrupted ) on my side, so now **donnie work fine of this**...Nice! 
I can say too that -v0.7 has reached a stable version.
Thx...
